# Generated by Django 5.1.1 on 2024-10-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundleorder",
            name="service_id",
            field=models.CharField(max_length=20),
        ),
    ]
