# Generated by Django 5.1.1 on 2024-10-18 13:42

import API.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_bundleorder_service_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicedetailhistory',
            old_name='order_notes',
            new_name='packing_instructions',
        ),
        migrations.RenameField(
            model_name='shipmentdetails',
            old_name='order_notes',
            new_name='packing_instructions',
        ),
        migrations.RemoveField(
            model_name='servicedetailhistory',
            name='from_inventory',
        ),
        migrations.RemoveField(
            model_name='servicedetailhistory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='shipmentdetails',
            name='from_inventory',
        ),
        migrations.RemoveField(
            model_name='shipmentdetails',
            name='quantity',
        ),
        migrations.AddField(
            model_name='servicedetailhistory',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailhistory',
            name='additional_format',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailhistory',
            name='additional_format_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=API.models.ServiceDetailHistory.pdf_directory_path_additional),
        ),
        migrations.AddField(
            model_name='servicedetailhistory',
            name='additional_format_text',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailhistory',
            name='additional_service',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailhistory',
            name='bin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.bin'),
        ),
        migrations.AddField(
            model_name='servicedetailhistory',
            name='box_label',
            field=models.FileField(blank=True, default=None, null=True, upload_to=API.models.ServiceDetailHistory.path_to_file_fba),
        ),
        migrations.AddField(
            model_name='servicedetailhistory',
            name='bundle_quantity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailhistory',
            name='fnsku',
            field=models.FileField(blank=True, default=None, null=True, upload_to=API.models.ServiceDetailHistory.path_to_file_fnsku),
        ),
        migrations.AddField(
            model_name='servicedetailhistory',
            name='no_bundles',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailhistory',
            name='quantity_from_inventory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailhistory',
            name='quantity_from_new_shipment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicedetailhistory',
            name='quantity_from_recent_received',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentdetails',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='shipmentdetails',
            name='additional_format',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='shipmentdetails',
            name='additional_format_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=API.models.ShipmentDetails.pdf_directory_path_additional),
        ),
        migrations.AddField(
            model_name='shipmentdetails',
            name='additional_format_text',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipmentdetails',
            name='additional_service',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='shipmentdetails',
            name='bin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.bin'),
        ),
        migrations.AddField(
            model_name='shipmentdetails',
            name='bundle_quantity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='shipmentdetails',
            name='no_bundles',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='shipmentdetails',
            name='quantity_from_inventory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentdetails',
            name='quantity_from_new_shipment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentdetails',
            name='quantity_from_recent_received',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetailhistory',
            name='placed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentdetails',
            name='placed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
