# Generated by Django 5.1.1 on 2024-10-20 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "API",
            "0003_rename_order_notes_servicedetailhistory_packing_instructions_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="dimension",
            old_name="Inventory_id",
            new_name="inventory_id",
        ),
        migrations.AddField(
            model_name="inventory",
            name="no_bundles",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventory",
            name="pack_size",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="received",
            name="tracking_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="BundleInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "inventory_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Inventory_bundle_inventory",
                        to="API.inventory",
                    ),
                ),
                (
                    "other_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="inventory_second_item",
                        to="API.item",
                    ),
                ),
            ],
        ),
    ]
