# Generated by Django 5.1.1 on 2024-10-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_rename_inventory_id_dimension_inventory_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='received_service',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='received_service',
            name='service_code',
        ),
        migrations.AlterField(
            model_name='received_service',
            name='item_id',
            field=models.CharField(blank=True, default=True, max_length=20, null=True),
        ),
    ]
