# Generated by Django 5.1.1 on 2024-10-22 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0005_remove_received_service_category_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="charges",
            name="category_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="charges_category_id",
                to="API.ordercategory",
            ),
        ),
        migrations.AddField(
            model_name="charges",
            name="note",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
