# Generated by Django 5.1.1 on 2024-10-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_charges_category_id_charges_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='charges',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='charges_item_id', to='API.item'),
        ),
        migrations.AlterField(
            model_name='bundleorder',
            name='service_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='service_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='palletdimension',
            name='service_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='service_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servicedetailhistory',
            name='service_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipmentdetails',
            name='service_id',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='ServiceBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=50)),
                ('item_id', models.CharField(max_length=20)),
                ('service_code', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicebox_box', to='API.dimension')),
            ],
        ),
    ]
