# Generated by Django 5.1.1 on 2024-11-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_charges_item_id_alter_bundleorder_service_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(default=None, max_length=50)),
                ('address', models.CharField(default=None, max_length=100)),
                ('city', models.CharField(default=None, max_length=50)),
                ('state', models.CharField(default=None, max_length=50)),
                ('country', models.CharField(default=None, max_length=50)),
                ('zip_code', models.CharField(default=None, max_length=10)),
                ('phone', models.CharField(default=None, max_length=15)),
                ('email', models.EmailField(default=None, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='usersextended',
            name='warehouses',
            field=models.ManyToManyField(blank=True, related_name='users', to='API.warehouse'),
        ),
    ]
