# Generated by Django 5.1.1 on 2024-11-26 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_warehouse_usersextended_warehouses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')], unique=True, verbose_name='Clearance Level')),
                ('name', models.CharField(max_length=50, verbose_name='Clearance Name')),
            ],
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='zip_code',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='usersextended',
            name='clearance_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.clearancelevel', verbose_name='Clearance Level'),
        ),
    ]
