# Generated by Django 5.1.1 on 2024-11-26 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_clearancelevel_alter_warehouse_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersextended',
            name='role',
        ),
    ]
