# Generated by Django 5.1.4 on 2025-02-04 13:28

import Orders.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('Structures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubOrders',
            fields=[
                ('sub_order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('no_bundles', models.IntegerField(blank=True, default=None, null=True)),
                ('bundle_quantity', models.IntegerField(blank=True, default=None, null=True)),
                ('additional_order', models.CharField(blank=True, max_length=40, null=True)),
                ('additional_format', models.CharField(blank=True, max_length=40, null=True)),
                ('additional_format_text', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('additional_format_file', models.FileField(blank=True, default=None, null=True, upload_to=Orders.models.SubOrders.pdf_directory_path_additional)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('fnsku_label', models.FileField(blank=True, default=None, null=True, upload_to=Orders.models.SubOrders.pdf_directory_path_fnksu)),
                ('box_label', models.FileField(blank=True, default=None, null=True, upload_to=Orders.models.SubOrders.pdf_directory_path_fba)),
                ('placed_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('active_order_start_date', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('phase', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('picked', 'Picked'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=15, null=True)),
                ('dispute_from_client', models.BooleanField(blank=True, default=False, null=True)),
                ('dispute_from_warehouse', models.BooleanField(blank=True, default=False, null=True)),
                ('dispute_note', models.CharField(blank=True, max_length=100, null=True)),
                ('bundle', models.BooleanField(blank=True, default=False, null=True)),
                ('packing_instructions', models.CharField(blank=True, max_length=100, null=True)),
                ('pallet', models.BooleanField(blank=True, default=False, null=True)),
                ('item_id', models.ManyToManyField(related_name='item_id_sub_order', to='Inventory.item')),
                ('location_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Structures.locations')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_id_sub_order', to='Structures.orders')),
            ],
        ),
        migrations.CreateModel(
            name='SubOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.item')),
                ('sub_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.suborders')),
            ],
        ),
        migrations.CreateModel(
            name='PalletDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=3, max_digits=10)),
                ('width', models.DecimalField(decimal_places=3, max_digits=10)),
                ('height', models.DecimalField(decimal_places=3, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('shipped', models.BooleanField(blank=True, default=False, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('pallet_label', models.FileField(blank=True, null=True, upload_to='')),
                ('inventory_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.inventory')),
                ('sub_order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.suborders')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=3, max_digits=10)),
                ('width', models.DecimalField(decimal_places=3, max_digits=10)),
                ('height', models.DecimalField(decimal_places=3, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('box_quantity', models.IntegerField()),
                ('item_quantity', models.IntegerField()),
                ('shipped', models.BooleanField(blank=True, default=False, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('box_label', models.FileField(blank=True, null=True, upload_to='')),
                ('inventory_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.inventory')),
                ('pallet', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.palletdimension')),
                ('sub_order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.suborders')),
            ],
        ),
    ]
