# Generated by Django 5.1.4 on 2025-02-07 12:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('Structures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('FBA', 'FBA'), ('FBM', 'FBM'), ('Storage', 'Storage'), ('Other', 'Other')], max_length=10)),
                ('order_name', models.CharField(max_length=50, null=True)),
                ('order_charge', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('completed', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('completed_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubOrders',
            fields=[
                ('sub_order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('no_bundles', models.IntegerField(blank=True, default=None, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('order_placed_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('order_start_date', models.DateTimeField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('picked', 'Picked'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=15, null=True)),
                ('dispute_from_client', models.BooleanField(blank=True, default=False, null=True)),
                ('dispute_from_warehouse', models.BooleanField(blank=True, default=False, null=True)),
                ('dispute_from_va', models.BooleanField(blank=True, default=False, null=True)),
                ('dispute_note_client', models.CharField(blank=True, max_length=255, null=True)),
                ('dispute_note_warehouse', models.CharField(blank=True, max_length=255, null=True)),
                ('dispute_note_va', models.CharField(blank=True, max_length=255, null=True)),
                ('bundle', models.BooleanField(blank=True, default=False, null=True)),
                ('packing_instructions', models.CharField(blank=True, max_length=100, null=True)),
                ('pallet', models.BooleanField(blank=True, default=False, null=True)),
                ('from_vendor', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_id_sub_order', to='Inventory.item')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id_sub_order', to='Orders.orders')),
                ('sub_order_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_order_type_sub_order', to='Structures.services')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_sub_order', to='Structures.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='SubOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.item')),
                ('sub_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.suborders')),
            ],
        ),
        migrations.CreateModel(
            name='SubOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='labels/')),
                ('format', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('format_width', models.IntegerField(blank=True, default=0, null=True)),
                ('format_height', models.IntegerField(blank=True, default=0, null=True)),
                ('sub_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.suborders')),
            ],
        ),
        migrations.CreateModel(
            name='PalletDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=3, max_digits=10)),
                ('width', models.DecimalField(decimal_places=3, max_digits=10)),
                ('height', models.DecimalField(decimal_places=3, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('shipped', models.BooleanField(blank=True, default=False, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('sub_order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.suborders')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=3, max_digits=10)),
                ('width', models.DecimalField(decimal_places=3, max_digits=10)),
                ('height', models.DecimalField(decimal_places=3, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('box_quantity', models.IntegerField()),
                ('item_quantity', models.IntegerField()),
                ('shipped', models.BooleanField(blank=True, default=False, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('sub_order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.suborders')),
            ],
        ),
    ]
