# Generated by Django 5.1.4 on 2025-02-03 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suborders',
            old_name='active_service_start_date',
            new_name='active_order_start_date',
        ),
        migrations.RenameField(
            model_name='suborders',
            old_name='additional_service',
            new_name='additional_order',
        ),
        migrations.RemoveField(
            model_name='suborders',
            name='service_id',
        ),
        migrations.AlterField(
            model_name='suborders',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_id_sub_order', to='Orders.orders'),
        ),
    ]
