# Generated by Django 5.1.4 on 2025-02-07 12:22

import Billing.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('balance_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_charge', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_id_custom_rates', to='Orders.orders')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_custom_rates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to=Billing.models.dynamic_upload_path)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid', models.BooleanField(default=False)),
                ('date_created', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Orders.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('charge_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_charged', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='charges_service_id', to='Orders.suborders')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='charges_user_id', to=settings.AUTH_USER_MODEL)),
                ('invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='charges_invoice_id', to='Billing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Billing.invoice')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
