# Generated by Django 5.1.4 on 2025-02-03 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0001_initial'),
        ('Orders', '0002_rename_active_service_start_date_suborders_active_order_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrates',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_id_custom_rates', to='Orders.orders'),
        ),
    ]
