# Generated by Django 5.1.4 on 2025-02-04 13:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Structures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'item_id')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('FBA', 'FBA'), ('FBM', 'FBM'), ('Storage', 'Storage'), ('Other', 'Other')], max_length=10)),
                ('pack_size', models.IntegerField()),
                ('no_bundles', models.IntegerField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('boxes', models.IntegerField(default=0)),
                ('pallet', models.BooleanField(default=False)),
                ('charge_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Structures.orders', verbose_name='Charge By')),
                ('location_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_id_inventory', to='Structures.locations')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_id_inventory', to='Inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='Discard',
            fields=[
                ('discard_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField()),
                ('date_discarded', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField()),
                ('dimension_id', models.IntegerField(null=True)),
                ('boxes', models.IntegerField(default=0)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discard_client_id', to=settings.AUTH_USER_MODEL)),
                ('location_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discard_bin_id', to='Structures.locations')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discard_item_id', to='Inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='BundleInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inventory_bundle_inventory', to='Inventory.inventory')),
                ('other_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_second_item', to='Inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='Removal',
            fields=[
                ('removal_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField(null=True)),
                ('dimension_id', models.IntegerField(null=True)),
                ('boxes', models.IntegerField(default=0)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='removal_client_id', to=settings.AUTH_USER_MODEL)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_item_id', to='Inventory.item')),
                ('location_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='removal_bin_id', to='Structures.locations')),
            ],
        ),
    ]
