# Generated by Django 5.1.4 on 2025-02-07 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(default=None, max_length=50)),
                ('address', models.CharField(default=None, max_length=100, null=True)),
                ('city', models.CharField(default=None, max_length=50, null=True)),
                ('state', models.CharField(default=None, max_length=50, null=True)),
                ('country', models.CharField(default=None, max_length=50, null=True)),
                ('zip_code', models.CharField(default=None, max_length=10, null=True)),
                ('phone', models.CharField(default=None, max_length=15, null=True)),
                ('email', models.EmailField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_type', models.CharField(choices=[('Bin', 'Bin'), ('Other', 'Other')], max_length=10)),
                ('location_name', models.CharField(max_length=50)),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Structures.warehouse')),
            ],
        ),
    ]
