# Generated by Django 5.1.4 on 2025-02-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
        ('Structures', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Orders',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='service_charge',
            new_name='order_charge',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='service_id',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='service_name',
            new_name='order_name',
        ),
    ]
