# Generated by Django 5.1.4 on 2025-02-04 13:28

import Received.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Received',
            fields=[
                ('tracking_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('tracking_type', models.CharField(blank=True, max_length=20, null=True)),
                ('date_received', models.DateTimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('assigned', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recieved_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Received_Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=20)),
                ('item_id', models.CharField(blank=True, default=True, max_length=20, null=True)),
                ('tracking_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_received_service', to='Received.received')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Received.models.ReceivedImage.path_to_image)),
                ('received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Received.received')),
            ],
        ),
    ]
