# Generated by Django 5.1.4 on 2025-02-04 13:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Structures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OTP_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secondary Email')),
                ('clearance_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, verbose_name='Clearance Level')),
                ('tax_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tax ID')),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Address')),
                ('billing_type', models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Bimonthly', 'Bimonthly')], default='Monthly', max_length=10, null=True, verbose_name='Billing Type')),
                ('llc_name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='LLC Name')),
                ('state', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='State')),
                ('city', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='City')),
                ('zip', models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip Code')),
                ('date_created', models.DateField(default=django.utils.timezone.now, null=True)),
                ('last_logout', models.DateTimeField(blank=True, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended', to=settings.AUTH_USER_MODEL, verbose_name='Username')),
                ('warehouses', models.ManyToManyField(blank=True, related_name='users', to='Structures.warehouse')),
            ],
        ),
    ]
