# Generated by Django 5.1.4 on 2025-01-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantUser',
        ),
    ]
