# Generated by Django 5.1.4 on 2025-01-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_usersextended_clearance_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersextended',
            name='clearance_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, verbose_name='Clearance Level'),
        ),
    ]
